name: Lighthouse CI

on:
  workflow_run:
    workflows: ['Deploy Astro site to Pages'] # 👈 must match your deploy workflow's `name`
    types:
      - completed

env:
  ASTRO_TELEMETRY_DISABLED: '1'

jobs:
  lhci:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Enable Corepack
        run: corepack enable

      - name: Run Lighthouse CI
        run: |
          yarn dlx @lhci/cli autorun \
            --collect.url=https://joseph-turner.github.io \
            --collect.settings.preset=desktop
